#!/bin/bash
echo Watcherino building...
echo ==================================
echo installing libraries
go get gopkg.in/alecthomas/kingpin.v2
go get github.com/fsnotify/fsnotify
go install github.com/fsnotify/fsnotify
echo building for macos
mkdir dist/mac
GOOS=darwin GOARCH=amd64 go build -o dist/mac/watcherino watcherino.go
echo building for linux
mkdir dist/linux
GOOS=linux GOARCH=amd64 go build -o dist/linux/watcherino watcherino.go
echo building for windows
mkdir dist/win
GOOS=windows GOARCH=amd64 go build -o dist/win/watcherino.exe watcherino.go
