#!/bin/bash
echo Watcherino building...
echo ==================================
echo installing libraries
go get gopkg.in/alecthomas/kingpin.v2
go get github.com/fsnotify/fsnotify
go install github.com/fsnotify/fsnotify
echo building for macos
GOOS=darwin GOARCH=amd64 go build -o dist/watcherino-mac watcherino.go
echo building for linux
GOOS=linux GOARCH=amd64 go build -o dist/watcherino watcherino.go
echo building for windows
GOOS=windows GOARCH=amd64 go build -o dist/watcherino.exe watcherino.go
